# Generated by Django 5.0.6 on 2024-05-21 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borehole',
            fields=[
                ('borehole_id', models.AutoField(db_column='borehole_id', primary_key=True, serialize=False)),
                ('location', models.CharField(db_column='location', max_length=255)),
                ('depth', models.DecimalField(db_column='depth', decimal_places=2, max_digits=10)),
                ('diameter', models.DecimalField(db_column='diameter', decimal_places=2, max_digits=5)),
                ('sensor_id', models.CharField(db_column='sensor_id', max_length=50)),
            ],
            options={
                'db_table': 'Borehole',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=150, unique=True)),
                ('email', models.EmailField(db_column='email', max_length=255, unique=True)),
                ('phone_number', models.CharField(db_column='phone_number', max_length=20)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('sensor_id', models.CharField(db_column='sensor_id', max_length=50, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
                ('water_level', models.DecimalField(db_column='water_level', decimal_places=2, max_digits=5)),
                ('temperature', models.DecimalField(db_column='temperature', decimal_places=2, max_digits=5)),
                ('pressure', models.DecimalField(db_column='pressure', decimal_places=2, max_digits=5)),
                ('water_quality', models.CharField(db_column='water_quality', max_length=100)),
                ('borehole', models.ForeignKey(db_column='borehole_id', on_delete=django.db.models.deletion.CASCADE, to='app_monitor.borehole')),
            ],
            options={
                'db_table': 'SensorData',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='borehole',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app_monitor.user'),
        ),
    ]
