# Generated by Django 5.0.6 on 2024-05-21 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borehole',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_monitor.user'),
        ),
    ]
